- name: "manage worker1 and 2"
  hosts: all
  become: true
  tasks:
  - name: "ensure Amit user exists"
    user:
      name: amit
      state: present
  - name: "ensure Alex user exists"
    user:
      name: alex
      state: present
  - name: "Install Finger"
    apt:
        name: finger
        state: present
        update_cache: yes 
      
